[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[dev]
  framework = "#custom"
  command = "python main.py"
  targetPort = 5000
  port = 8888
  publish = "public"
  autoLaunch = true